### ISSUE TITLE
Cannot load custom vit-b

### ISSUE THREAD

**Issue by constantinpape** [computational-cell-analytics/micro-sam#110]
Loading the finetuned `vit-b`s does not work.
```python
from micro_sam.util import get_sam_model

predictor = get_sam_model(model_type="vit_b_lm")
```
fails with a very long error message about parameter shape mismatches.

It works for the `vit_l` models. 

cc @anwai98

**Comment by anwai98** [comment]
Hi Constantin!

From what I see in the `get_sam_model`, it expects to change the model type to the respective model checkpoints (so ViT-b models would expect `vit_b` attribute in the model type), hence the size mismatch. Or did you try this already?

**Comment by constantinpape** [comment]
You mean this?
```python
    # Our custom model types have a suffix "_...". This suffix needs to be stripped
    # before calling sam_model_registry.
    model_type_ = model_type[:5]
    assert model_type_ in ("vit_h", "vit_b", "vit_l")
```
That just maps `vit_b_lm` -> `vit_b` and works as expected. So that is not the cause of the issue and would also result in a different error, because `sam_model_registry` just wouldn't accept the `model_type`.

**Comment by anwai98** [comment]
Hi Constantin. I cross-checked the models, and my guess is that the call for `vit_h_lm` / `vit_h_em` models call for ViT-b checkpoints. I caught it from :
- The first tuple of mismatch is the [`encoder_embed_dim`](https://github.com/facebookresearch/segment-anything/blob/main/segment_anything/build_sam.py), where it expects 1280, and we pass 768 (i.e. a ViT_b checkpoint)
- I checked via my bootstrapped method, and the predictor (/model) initialization worked fine.

Could you try to reupload the respective models from the directory and tell me if it works?
