### ISSUE TITLE
Clear annotations doesnt reset tracking state

### ISSUE THREAD

**Issue by constantinpape** [computational-cell-analytics/micro-sam#118]
Clear annotations doesnt reset `track_state` and `track_id` leading to errors thrown when there was a `division` segmentation before clearing the annotations, creating multiple `track_id` values in the dropdown which were meaningless after clearing the annotations.

_Originally posted by @Sagnik700 in https://github.com/computational-cell-analytics/micro-sam/issues/64#issuecomment-1660937153_

**Comment by constantinpape** [comment]
Hi @Sagnik700 ,
this should be fixed now with #117. Can you double check?
Thanks!

**Comment by Sagnik700** [comment]
Hey @constantinpape , I just had a look with the latest changes and it seems to be resolved! Thanks.
