### ISSUE TITLE
Reset track_state to track after a commit

### ISSUE THREAD

**Issue by Sagnik700** [computational-cell-analytics/micro-sam#129]
If the `track_state` was kept in `division` before clicking on Commit, the new annotation started with the track_state being in `division` rather than being in `track`. If it is not noticed then it leads to multiple errors and wrong segmentations, so after committing every track, the `track_state` should be reset to `track`

**Comment by constantinpape** [comment]
Hi Sagnik,
thanks for reporting. I gave this a try in #132 ,  but unfortunately it doesn't work as expected.
I will need to dig deeper, but probably won't have time before I go on holidays.

**Comment by constantinpape** [comment]
After reviewing the design, this unfortunately is not possible: the track state always refers to the last point that was placed, so updating it would undo the division label.
