### ISSUE TITLE
Embedding creation or selection prompt in Windows 10 not functioning properly

### ISSUE THREAD

**Issue by Sagnik700** [computational-cell-analytics/micro-sam#130]
When the embeddings do not match the dataset, the prompt to select new embeddings or generate new embeddings come up, but the functionality for `Select different file` and `Create new file` is not working as expected. This testing was done in Windows 10 machine and the two videos attached below display the issue that is prevalent.
1. After clicking on `Select different file`, the file explorer opens for selection but closes immedietly, and this happens for **4 times** after which napari opens anyhow probably **ignoring** the changes in the embeddings
2. After clicking on `Create new file`, the file explorer opens but putting a new name for the embeddings and clicking on Open does not work and the window appears again, and this happens for **4 times** after which napari opens anyhow probably **ignoring** the changes in the embeddings

https://github.com/computational-cell-analytics/micro-sam/assets/23014134/171ef662-fb58-45e5-ad05-d22d10746551

https://github.com/computational-cell-analytics/micro-sam/assets/23014134/00a66825-4159-4152-9ddc-cc818adbd879

**Comment by paulhfu** [comment]
Hi @constantinpape and @Sagnik700,
Thank you for testing.
To the first point:

I added the requirement, that the embeddinfsfile has a .zarr extension. If you give it a different file, the dialog will open again to give another chance. In total you have 4 tries to type in a "correct" path. Should I relax this requirement to any path conform name (allowing dots and spaces)?

To the second point:

I tested on windows once, but there where changes since then. I will check it again.

**Comment by constantinpape** [comment]
> Should I relax this requirement to any path conform name (allowing dots and spaces)?

Yes, please relax the requirement, and then just add the zarr extension if it's not given by the user.
So something like
```python
if not path.suffix == ".zarr":
    path = path.with_suffix(".zarr")
``` 

> I tested on windows once, but there where changes since then. I will check it again.

:+1:

**Comment by constantinpape** [comment]
@Sagnik700 this should be fixed now by #133 .
Can you please double check? Thanks!

**Comment by constantinpape** [comment]
@Sagnik700 can you check if this problem is still there? Thanks!

**Comment by Sagnik700** [comment]
@constantinpape @paulhfu sorry this took some time, but I just checked it now with latest changes and it seems to be fixed. We can close this issue now.

**Comment by constantinpape** [comment]
Thanks for checking @Sagnik700
