### ISSUE TITLE
Provide visual feedback for embedding computation via GUI

### ISSUE THREAD

**Issue by constantinpape** [computational-cell-analytics/micro-sam#161]
Currently there is no "visual feedback" when a user clicks the annotator button. If embeddings have to be precomputed it can take quite some time for the annotation tool to open, so the user might think nothing is happening at all.

It would be good to provide some visual feedback here: open a message that says that embeddings are precomputed, and ideally also show a progress button (re-using the `tqdm` one already used).

Reported by @sushmita-nair 
cc @paulhfu

**Comment by GenevieveBuckley** [comment]
This would be very usefui!

**Comment by constantinpape** [comment]
This issue is a bit outdated due to upcoming plans re the plugin. I will close it and create new and more relevant ones.
