### ISSUE TITLE
Min object size cannot be set to value > 999

### ISSUE THREAD

**Issue by constantinpape** [computational-cell-analytics/micro-sam#171]
The `min object sjze` field in the automatic segmentation window cannot be set to a value larger than 999.
It is initialized with a value of 100, but for some cases it would be beneficial to set it to larger values.
See

![image](https://github.com/computational-cell-analytics/micro-sam/assets/4263537/7d44d0d9-459d-45e2-9c9a-d17c8a28a09f)

The corresponding magicgui plugin is created here: https://github.com/computational-cell-analytics/micro-sam/blob/master/micro_sam/sam_annotator/annotator_2d.py#L50

@tlambert03 are there any magicgui tricks to enable passing larger numbers for an int field?

**Comment by tlambert03** [comment]
Pass in a max to the corresponding widget: https://pyapp-kit.github.io/magicgui/api/widgets/bases/#magicgui.widgets.bases.RangedWidget

**Comment by tlambert03** [comment]
https://pyapp-kit.github.io/magicgui/type_map/#examples

**Comment by constantinpape** [comment]
Thanks @tlambert03! (Issue solved in < 30 min :) )

**Comment by constantinpape** [comment]
Fixed by 9bad755.
