### ISSUE TITLE
use label from detect model to prompt SAM 

### ISSUE THREAD

**Issue by aiyou9** [computational-cell-analytics/micro-sam#194]
Yolo NAS with SAM
https://github.com/RATHOD-SHUBHAM/SegmentAnything

how_to_use_yolo8v_with_sam
https://github.com/RATHOD-SHUBHAM/SegmentAnything/blob/master/how_to_use_yolo8v_with_sam.ipynb

**Comment by constantinpape** [comment]
Hi @aiyou9,
can you expand on this issue? Are you proposing integration of object detection for box prompt generation? Please note that this repository is focused on application biomedical imaging.

**Comment by aiyou9** [comment]
The challenges in using SAM in this project：
https://github.com/XiaodanXing/SAM4organoid#method-description


in the impoverment of SAM, I  think the box label from object detection may help to run SAM in 3 terms 
1. prompt for SAM
2. seg a ROI sub-area to avoid surrounding similar image interference
3. From  the surrounding boxes of a certain box, compare the overlapping parts, and automatically find the position of the negative marker point  to prompt SAM

 if this repository is focused on application biomedical imaging, this issue may be not suitable to go on,

mostly zero-shot segment is base on  fine-tune SAM, some good work based on SAM

https://github.com/yatengLG/ISAT_with_segment_anything/blob/master/docs/features%20description.md#3contour-mode

so I close this issue
