### ISSUE TITLE
Explore widget containers

### ISSUE THREAD

**Issue by constantinpape** [computational-cell-analytics/micro-sam#200]
We could use widget containers to group all relevant functionality for a plugin in one container.
See https://pyapp-kit.github.io/magicgui/api/widgets/Container/ for widget containers.

cc @DragaDoncila (@GenevieveBuckley told us that you were also looking into a demo PR for this).

@paulhfu : probably wait to look into this till Draga answers ;).

**Comment by DragaDoncila** [comment]
@constantinpape @paulhfu  👋 thanks for the ping! I have just [opened the PR ](https://github.com/napari/cookiecutter-napari-plugin/pull/168)to the napari plugin cookiecutter adding a `Container` example. Let me know if it seems like it would aid what you're trying to do here, if there's any questions I can answer, or if there's missing features you'd like us to explore!

**Comment by constantinpape** [comment]
We have adopted widget containers in #304. Thanks for the example you have added in the cookiecutter repo @DragaDoncila - this was very helpful for the implementation.
