### ISSUE TITLE
Best design for plugins?

### ISSUE THREAD

**Issue by constantinpape** [computational-cell-analytics/micro-sam#206]
Currently, the annotation tools are all implemented using separate functions that duplicate quite some functionality.
It would be better to find a design that enables sharing more of the common functionality between them.
There are two different approaches:
- Using a class and inheritance design.
  - It's a bit unclear to us how exactly this would work with magicgui, but maybe we could use https://github.com/hanjinliu/magic-class 
- Use auxiliary functions that refactor the common functionality. This is the current approach, but many things are not refactored yet. The util functions are in https://github.com/computational-cell-analytics/micro-sam/blob/master/micro_sam/sam_annotator/util.py

**Comment by tlambert03** [comment]
> It's a bit unclear to us how exactly this would work with magicgui

also consider dataclasses: https://pyapp-kit.github.io/magicgui/dataclasses/

**Comment by constantinpape** [comment]
We have decided now to go with a "normal" class design and use inheritance, see #304. I decided against dataclasses because the logic for initializing the plugins here is a bit more complex and requires a full fledged init.
