### ISSUE TITLE
precompute_embeddings are not using GPU

### ISSUE THREAD

**Issue by Conecsion** [computational-cell-analytics/micro-sam#230]
Hi I wonder how can I use GPUs to calculate embeddings in CLI. 

It seems fine when I run the program from micro_sam.annotater GUI interface, but when I execute micro_sam.annotater_3d or micro_sam.precompute_embeddings in bash CLI, GPUs just won't work.

My commands
```shell
micro_sam.annotator_3d -i ./img_stack.tif \
-e ./embeddings.zarr \
--model_type vit_h_em \
--tile_shape 2048 2048 --halo 1024 1024
``` 
and
```shell
micro_sam.precompute_embeddings -i data/register1_stack.tif \
-o precompute_embeddings.zarr \
-m vit_h_em \
--tile_shape 2048 2048 --halo 1024 1024 -n 3
```

I'm pretty sure that my nvidia-driver, cuda toolkits and pytorch are functioning normally. I'm using Ubuntu 22.04 and the latest micro-sam is  built from source

**Comment by constantinpape** [comment]
Hi @Conecsion,

> GPUs just won't work.

How do you know that the GPU doesn't work? Is the computation taking unexpectedly long, or are you checking its usage via `nvidia-smi`?

> I'm pretty sure that my nvidia-driver, cuda toolkits and pytorch are functioning normally. I'm using Ubuntu 22.04 and the latest micro-sam is built from source

Can you check if the `torch` installation can use the GPU? For this:
- Activate the environment in which `micro_sam` is installed.
- Run `python -c "import torch; print(torch.cuda.is_available())"`

If it prints `True` the GPU can be used and `micro_sam` should automatically use it. If it prints `False` the GPU can't be used.

In the latter case please run `conda list | grep torch` and paste the output here.

**Comment by constantinpape** [comment]
Closed due to inactivity. @Conecsion you can reopen this if the issue persists, please see my previous comment for the information we would need to help you.
