### ISSUE TITLE
Codecov report uploads not working

### ISSUE THREAD

**Issue by GenevieveBuckley** [computational-cell-analytics/micro-sam#234]
The code coverage reports are not being uploaded to codecov.io properly for our master branch. 

### Error message
[Here's a CI job example where the code coverage upload fails](https://github.com/computational-cell-analytics/micro-sam/actions/runs/6553635489/job/17799282963)
```
Codecov report uploader 0.6.3
[2023-10-17T22:46:11.814Z] ['info'] => Project root located at: /home/runner/work/micro-sam/micro-sam
[2023-10-17T22:46:11.815Z] ['info'] -> Token found by environment variables
[2023-10-17T22:46:11.817Z] ['error'] There was an error running the uploader: Token found by environment variables with length 50 did not pass validation
```

### Discussion
The error suggests there is something wrong with our token. This is confusing, because I don't think anything has changed about the token.

 Clearly it was working well before, since we do see reports uploaded for the "codecov-report" and "gui-tests-plus-codecov" branches on codecov.io ([like this](https://app.codecov.io/gh/computational-cell-analytics/micro-sam/tree/codecov-report))

### Something to try
@constantinpape can you try generating a new token in codecov and updating our github secret?

Then you can re-run the test.yaml github CI manually from this page, and see if that works:
https://github.com/computational-cell-analytics/micro-sam/actions/workflows/test.yaml

**Comment by constantinpape** [comment]
It's working again in the PR: https://github.com/computational-cell-analytics/micro-sam/pull/243#issuecomment-1778429110. Not sure what's going on. I will check later if we now get reports for main.

**Comment by GenevieveBuckley** [comment]
Apparently it's not always super reliable - someone suggested I look at this blog post for an alternative https://hynek.me/articles/ditch-codecov-python/

**Comment by constantinpape** [comment]
> Apparently it's not always super reliable - someone suggested I look at this blog post for an alternative https://hynek.me/articles/ditch-codecov-python/

Ok, that looks like it's worth checking out.

For now I would suggest we focus on advancing the plugin though. I fear that getting this fully set up could be a time sink.
And it seems like codecov is working in PRs, just not for the master branch,

**Comment by constantinpape** [comment]
Now we also have coverage uploaded on master:

![image](https://github.com/computational-cell-analytics/micro-sam/assets/4263537/c2cf0508-aeeb-46df-accd-d3af0fa0ef18)

So I think this is indeed due to the unreliability of code-cov, and not a problem with the credentials.

**Comment by GenevieveBuckley** [comment]
Should we close this issue? 
There doesn't seem to be a specific action we can take. It seems like things are relatively ok here.
