### ISSUE TITLE
[feature require] auto create point prompt for subcellular structure insider cell, such as Dense liposomes

### ISSUE THREAD

**Issue by aiyou9** [computational-cell-analytics/micro-sam#236]
![image](https://github.com/computational-cell-analytics/micro-sam/assets/15712822/3a6c3230-9de8-4abc-988c-475c43ef704f)
A fine-tuned parameter bar in UI to tune opencv's algorithm to find the region of the image with the densest pixels, which is then used as the point prompt.

**Comment by constantinpape** [comment]
That sounds like an interesting idea. Would you be interested in contributing this? I am thinking about extensions for the automatic segmentation functionality, and this would be a good candidate.

If you're interested, then the next step would be a simple prototype script for the proposed functionality.

**Comment by aiyou9** [comment]
Sorry, I can't help to so this issue. I am a  student in biology with a few python coding skills,  I did know how to do deep learn coding  work.

**Comment by constantinpape** [comment]
Ok, I will see when we will come around to work on this, but it will probably be a while.
