### ISSUE TITLE
Fix hash comparison and investigate pop-up warnings

### ISSUE THREAD

**Issue by constantinpape** [computational-cell-analytics/micro-sam#262]
A follow up piece of work for this might be trying to figure out why we don't see the hash comparison working (hint: we think it's because that happens in the thread worker), and/or trying to make a pop up dialog box to make the error more obvious than just printing to a terminal the user might not see.

For future work, we might like to investigate pop up dialog boxes more generally. It could be good for both error messages, and for informing the user when the embedding computation has completed (good for user feedback in both very short, and very long running computations). Possibly low priority, though.

_Originally posted by @GenevieveBuckley in https://github.com/computational-cell-analytics/micro-sam/issues/235#issuecomment-1791932748_

**Comment by GenevieveBuckley** [comment]
1. The reason we didn't see the hash comparison working is that it only raised a user warning, not an actual error. After upgrading to a RuntimeError if the data_signature hash comparison fails, we see a popup dialog box in napari.

2. I think we should stick with using the napari popup error dialog boxes. (I know I was the one to suggest we look into dialog boxes for little "finished!" messages, etc. but perhaps this is not the best idea. One thing I have done is to move *all* the long running computation stuff into the thread worker which shows the progress bar, so there's a little less confusion about whether it ran and did something or not)

**Comment by constantinpape** [comment]
Thanks @GenevieveBuckley! I will close this for now and we can reopen it if we decide to look into pop-up boxes later on. I agree that this is not a high priority, so we should focus on other things first.

**Comment by GenevieveBuckley** [comment]
That's a good plan. I did find some weird things about the error pop ups in napari, so I've made an issue over there: https://github.com/napari/napari/issues/6420
