### ISSUE TITLE
Use a consistent cache directory

### ISSUE THREAD

**Issue by constantinpape** [computational-cell-analytics/micro-sam#264]
We currently use different cache directories for saving the models vs. saving the sample image data.
- The models use `$HOME/.sam_models`.
- The sample data uses `$HOME/.cache/micro-sam`

It would be good to be consistent here and I think `$HOME/.cache/micro_sam` is a good choice. For the models we could use  `$HOME/.cache/micro_sam/models`.

What do you think @GenevieveBuckley ?

**Comment by GenevieveBuckley** [comment]
I say it's a good idea and I'm happy to do that.

**Comment by constantinpape** [comment]
Ok! The path for the downloads is currently set here: https://github.com/computational-cell-analytics/micro-sam/blob/master/micro_sam/util.py#L50

The intention behind this code was to enable changing the cache directory via the `SAM_MODELS` environment variable. But this is not documented anywhere so we can change it.

My suggestion would be that we introduce a new environment variable `MICRO_SAM_CACHE` instead that defaults to `$HOME/.cache/micro_sam`. We should keep the option to set a different cache path for systems where the storage in `$HOME` is limited (e.g. computer clusters).
