### ISSUE TITLE
Should we add data_signature to the AnnotatorState attributes?

### ISSUE THREAD

**Issue by GenevieveBuckley** [computational-cell-analytics/micro-sam#266]
Saved zarr files with image embeddings now contain a "data_signature" hash, so we can be sure to match which input image was used to create which image embeddings (https://github.com/computational-cell-analytics/micro-sam/pull/67/files). Should we add data_signature as an attribute to `AnnotatorState`? 

I found it handy to have for reassurance things were behaving correctly while developing code, possibly it could be useful to have more generally too.

Potential complication: circular imports
* `micro_sam.sam_annotator._state.py` imports `ImageEmbeddings` from `micro_sam.util.py`
* But if we wanted to import `AnnotatorState` from `micro_sam.sam_annotator._state.py` and set the data_signature attribute... well, a lot of those functions (`_compute_2d`, `_precompute_2d`, etc.) live in `micro_sam.util.py`. That would create a circular import problem. We'd probably need to figure out the code structure a little better so things are clearer.

**Comment by constantinpape** [comment]
In general I think this is a good idea. I haven't thought about the circular import problem yet though.

**Comment by constantinpape** [comment]
I will close this in favor of #332. Our goal is to handle the emebddings correctly (check whether they match the current image), where we store the data_signature is a technical detail. (I lean towards not storing them in the state right now to avoid having multiple places where this is stored and having to keep them in sync)
