### ISSUE TITLE
Use python-xxhash instead of sha256

### ISSUE THREAD

**Issue by constantinpape** [computational-cell-analytics/micro-sam#283]
That should be straightforward to do, pooch supports the [python-xxhash](https://github.com/ifduyue/python-xxhash) bindings. 

The docs even have this nice example about how to use it, you just append `xxh128:` to the start of the hash.
https://www.fatiando.org/pooch/latest/hashes.html#other-supported-hashes

```python
import datetime
import pooch

# Get the current data to store the files in separate folders
CURRENT_DATE = datetime.datetime.now().date()

GOODBOY = pooch.create(
    [...],
    registry={
        "store.zip": "xxh128:6a71973c93eac6c8839ce751ce10ae48",
    },
)
```

_Originally posted by @GenevieveBuckley in https://github.com/computational-cell-analytics/micro-sam/issues/36#issuecomment-1809426270_

**Comment by constantinpape** [comment]
cc @hfmaark , we have implemented download via pooch now (merged onto the dev branch). A contribution would be welcome in case you want to look into this.

**Comment by hmaarrfk** [comment]
on it. Gotta download all the file first....

* `openssl sha256 vit_h`: 1.7 seconds
* `xxh128sum vit_t` 0.3 seconds

the timing will really vary based on whether or not the file has been cached.

**Comment by constantinpape** [comment]
Done in #284.

**Comment by constantinpape** [comment]
From 0.5 onwards (will be released soon!) we will use xxhash as default and include it in the dependencies.
