### ISSUE TITLE
Saving computed image embeddings

### ISSUE THREAD

**Issue by Mobinapournemat** [computational-cell-analytics/micro-sam#285]
I'm utilizing the micro-SAM GUI, and as you're aware, the embedding computation is quite time-consuming without GPU. Following the computation, napari opens for interactive annotation. Could you guide me on the process of saving the computed embedding to prevent wasting time for the next time I wanted to use my dataset in micro-SAM GUI?

**Comment by constantinpape** [comment]
Hi @Mobinapournemat ,
happy to help! Here's an example video that shows how to do it for the 2d annotation tool (works the same for other tools):

https://github.com/computational-cell-analytics/micro-sam/assets/4263537/e325f415-c693-4814-a698-71048ada0b52

So note that if the embedding file does not exist yet, then you first need to create a folder (with ending `.zarr`) and then choose it.
If it exists already you can just select the corresponding folder via choose and the embeddings will be loaded.

Hope that helps, let me know if anything is still unclear!

**Comment by Mobinapournemat** [comment]
Thank you so much for your prompt response. I followed your instruction and the embedding saved successfully!
