### ISSUE TITLE
New object segmentations will overwrite older ones

### ISSUE THREAD

**Issue by GenevieveBuckley** [computational-cell-analytics/micro-sam#32]
I noticed that if a new object segmentation overlaps all or part of an older object, committing the new segmentation will overwrite the old one.

This is probably not a bug and is the desired behaviour. Making this more clearly understood in the user documentation is probably a useful idea.

Context: I shared some first impressions using micro-sam with Constantin. He asked me to write them down here, so we don't forget what was said.

**Comment by constantinpape** [comment]
This is implemented now. There is a button `preserve_committed`. If it's set the committed objects will not be over-written. It's set by default.

![image](https://github.com/computational-cell-analytics/micro-sam/assets/4263537/300fcc5b-b079-40d2-8b72-cc41ab76ebc9)
