### ISSUE TITLE
Pending updates with the new release

### ISSUE THREAD

**Issue by anwai98** [computational-cell-analytics/micro-sam#330]
Update the sample finetuning script for hela cells for the users to take inspiration from - https://github.com/computational-cell-analytics/micro-sam/blob/master/examples/finetuning/finetune_hela.py (it isn't using joint training - unless that's intended)

**Comment by constantinpape** [comment]
That's a good point! I would like to keep it optional there though. Do you want to make a quick PR for it that introduces a flag `train_instance_segmentation` (or so), and update the code so that it uses joint training if set to `True`?

**Comment by anwai98** [comment]
Sure, on it!

**Comment by anwai98** [comment]
Updated the finetuning example here - https://github.com/computational-cell-analytics/micro-sam/pull/338

**Comment by constantinpape** [comment]
Fixed by #338
