### ISSUE TITLE
questions about "ndim" parameter

### ISSUE THREAD

**Issue by JIBSN** [computational-cell-analytics/micro-sam#350]
Hi, 
Fristly thank you for you good job. I am now trying to run inference using automatic_mask_generator with one of your fintuned model, but I am confused about the "ndim" parameter and "i" parameter in the class AutomaticMaskGenerator. My input image is a RGB image with a shape of 2048x2048x3. When I set ndim=3, it can run properly with no error but it produced nothing. I haved tried ndim=2, it could produce 64 instances. Could you please give me a detailed  description about it？
Do the RGB images is treated as 2 dimensions?

**Comment by constantinpape** [comment]
Hi @JIBSN,
`ndim` refers to the spatial dimension, so if you have an RGB image you indeed need to set it to 2.
It would need to be set to 3 only for data with an extra spatial or time dimension, i.e. 3D or 2D + time data.
Regarding `i`; this is only needed for `ndim=3`, so you can ignore it.

> with one of your fintuned model

Note that you may need different settings for `pred_iou_thresh` and `stability_score_thresh` compared to the default values in the function. If you let me know which model you are using I can tell you which parameters should work well.
(We are in the process of  automating setting these parameters.)

**Comment by JIBSN** [comment]
Thank you for your quickly reply. I use the "vit_b_lm" model. Could you please give me some advices on setting  these parameters?

**Comment by constantinpape** [comment]
These parameters should work well:
```
pred_iou_thresh = 0.65, stability_score_thresh = 0.75
```
and you can set them in the `generate` method: https://github.com/computational-cell-analytics/micro-sam/blob/master/micro_sam/instance_segmentation.py#L479
