### ISSUE TITLE
Mamba installation from the doc gives CPU PyTorch

### ISSUE THREAD

**Issue by qin-yu** [computational-cell-analytics/micro-sam#356]
I guess you wanted users to have GPU enabled version by default?

```bash
mamba create -c conda-forge -n micro-sam micro_sam
mamba install -c conda-forge napari pyqt
```
then `conda list` gives:
```bash
pytorch                   2.1.0           cpu_generic_py311h8354fdb_2    conda-forge
```

**Comment by constantinpape** [comment]
> I guess you wanted users to have GPU enabled version by default?

I don't really think we should assume a default here, since many users might not have a GPU. But the documentation should indeed be extended to explain how to install a GPU based pytorch.

**Comment by constantinpape** [comment]
Fixed in 52c209a

**Comment by GenevieveBuckley** [comment]
Should we also update the conda-forge recipe `meta.yml` to use `pytorch-cuda`, instead of just CPU pytorch?

**Comment by constantinpape** [comment]
> Should we also update the conda-forge recipe `meta.yml` to use `pytorch-cuda`, instead of just CPU pytorch?

Is there a `pytorch-cuda` package on conda-forge? I did a (very quick) search but couldn't find anything. I only found [this discussion](https://discuss.pytorch.org/t/is-pytorch-cuda-going-to-be-registered-on-conda-forge/173968).

**Comment by GenevieveBuckley** [comment]
Ah, sorry. I guess [it exists](https://anaconda.org/pytorch/pytorch-cuda) but not on conda-forge specifically.
