### ISSUE TITLE
new M1 macOS runner available to open source

### ISSUE THREAD

**Issue by GenevieveBuckley** [computational-cell-analytics/micro-sam#369]
I just heard about this today, and I think it would be a very useful thing to update the github actions test matrix to include the M1 macOS runner.

https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

> ## GitHub Actions: Introducing the new M1 macOS runner available to open source!
> January 30, 2024
>
> Today, GitHub is excited to announce the launch of a new M1 macOS runner! This runner is available for all plans, free in public repositories, and eligible to consume included free plan minutes in private repositories. The new runner executes Actions workflows with a 3 vCPU, 7 GB RAM, and 14 GB of storage VM, which provides the latest Mac hardware Actions has to offer. The new runner operates exclusively on macOS 14 and to use it, simply update the `runs-on` key in your YAML workflow file to `macos-14`.

Related:
* https://github.com/computational-cell-analytics/micro-sam/issues/181
* https://github.com/computational-cell-analytics/micro-sam/pull/176
* https://github.com/computational-cell-analytics/micro-sam/pull/183

**Comment by constantinpape** [comment]
Fixed by #370
