### ISSUE TITLE
2d auto segmentation

### ISSUE THREAD

**Issue by Nal44** [computational-cell-analytics/micro-sam#384]
Hi,

I am testing 2d .

the auto segmentation runs, but doesn't give any outputs (with default parameters) ... ?

Any ideas ?

thanks
antho

**Comment by Nal44** [comment]
I can share an image if that helps ?

**Comment by constantinpape** [comment]
If you're using the `vit_b_lm` then you need to set lower values for the thresholds:
```
pred_iou_thresh = 0.65, stability_score_thresh = 0.75
```
We are working on setting these thresholds automatically, see #337.

**Comment by Nal44** [comment]
Thanks a lot,
using vit_b_lm and pred_iou_thresh = 0.65, stability_score_thresh = 0.75 as suggested :

see below : 
I think it needs it might need pre filtering or some normalization step ?
![automatic](https://github.com/computational-cell-analytics/micro-sam/assets/64991735/f875773d-86c8-4102-ad58-323a0ca66dcb)

Any ideas ?
thanks

**Comment by constantinpape** [comment]
Yes, I think the cells are too small for the current settings of the automated segmentation. I think it is more promising if you follow the approach outlined in #383. For this the automatic segmentation results don't really matter. As long as manual annotation either via point or bounding box prompts works well the refinement approach should work.
