### ISSUE TITLE
Error Encountered in annotator_with_finetuned_model.py when Using Automatic Segmentation in napari

### ISSUE THREAD

**Issue by Mobinapournemat** [computational-cell-analytics/micro-sam#388]
Hello, 

I'm trying to use my finetuned model for automatic segmentation using "annotator_with_finetuned_model.py" but when I click on the "Automatic Segmentation" button in napari, I get this error in my Python terminal:

`While emitting signal 'magicgui.widgets.PushButton.changed', an error occurred in callback 'magicgui.widgets._function_gui.FunctionGui.__init__.<locals>._disable_button_and_call'.
The args passed to the callback were: (False,)
This is not a bug in psygnal.  See 'TypeError' above for details.`

**Comment by constantinpape** [comment]
Hi @Mobinapournemat,
the most likely reason for this is that the model does not segment any objects. This often happens with the finetuned models, which need lower values for the `pred iou thresh` and the `stability score thresh`. You can change these in the GUI (see the screenshot below); and after you run the segmentation the first time updating the values and rerunning the segmentation will be fast.

![image](https://github.com/computational-cell-analytics/micro-sam/assets/4263537/96eb7a3a-d23c-488b-a8ff-752c1f26b7cb)

The best approach is the following: lower these thresholds to smaller values (e.g. 0.5 for both). This should segment the objects you are interested in, but may also segment unwanted objects. Then choose higher values for the thresholds until the unwanted objects disappear.

I hope this helps!

**Comment by constantinpape** [comment]
I assume the problem is fixed. Feel free to reopen if not.
