### ISSUE TITLE
Error - 2D segmentation using fine tuned models

### ISSUE THREAD

**Issue by AnalyticalSystemsResearch** [computational-cell-analytics/micro-sam#389]
Hi, Would appreciate feedback on the issue below. Thanks, ASR.

### Overview: 
Error encountered during 2D auto-segmentation when using fine-tuned models on 2d microscopy images (fluorescence, bright-field, phase).

### Issue: 
Running 2D annotator (w/ napari) and specifying some models leads to errors and no 2d auto-segmentation. 

Models working (no errors encountered):
vit_h, vit_b, vit_l, vit_t, vit_b_em_boundaries

Modules not working (errors encountered, see uploads):
vit_b_lm, vit_b_em_organelle

Can reproduce error when using alternative installation methods from https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#installation i.e. from installer. Similar issues when using through QuPath.

### Environment:
Installed micro_sam from mamba. See yaml for modules.

### Files uploaded:
- Yaml file for the GPU environment used
- error from console

[microSAM_environment.yml.zip](https://github.com/computational-cell-analytics/micro-sam/files/14260914/microSAM_environment.yml.zip)
[error_microSAM_vit_b_lm.py.zip](https://github.com/computational-cell-analytics/micro-sam/files/14261016/error_microSAM_vit_b_lm.py.zip)

**Comment by constantinpape** [comment]
Hi @AnalyticalSystemsResearch ,
this is most likely the same issue as in #388, the models need a lower threshold for the automatic segmentation setting.
Can you try lowering the thresholds as described in https://github.com/computational-cell-analytics/micro-sam/issues/388#issuecomment-1941554062?

Let me know if this helps!

**Comment by constantinpape** [comment]
I assume the problem is fixed. Feel free to reopen if not.
