### ISSUE TITLE
Better caching of embeddings

### ISSUE THREAD

**Issue by constantinpape** [computational-cell-analytics/micro-sam#40]
Currently the caching of embeddings is not aware of changing inputs. So if the image or any relevant parameters (e.g. tiling) change the napari annotator is not aware and things just break because the shapes etc. don't match anymore.

The best solution would probably be to hash all relevant things (the input image and the tiling params) and then warn or throw an error if the hash doesn't agree.

cc @GenevieveBuckley

**Comment by paulhfu** [comment]
I made a test with hashlib and the native Python hash function (where SipHash is the underlying algorithm):
There was some variation over trials but the native hash function was always fastest. I will continue using this one.

timeit.timeit(lambda: hash(input_.tobytes()), number=1)
0.0001364889999422303
timeit.timeit(lambda: hashlib.sha1(input_.tobytes()).hexdigest(), number=1)
0.000277818000085972
timeit.timeit(lambda: hashlib.sha256(input_.tobytes()).hexdigest(), number=1)
0.00028820699981224607
timeit.timeit(lambda: hashlib.md5(input_.tobytes()).hexdigest(), number=1)
0.000646958999823255
