### ISSUE TITLE
problem installing on windows

### ISSUE THREAD

**Issue by mocherry** [computational-cell-analytics/micro-sam#407]
Dear all,

I am trying to install micro_sam on Windows using miniconda3.
Being a beginner with using miniconda, I run into problems, although I have successfully installed other tools in this way.

I have created an environment: micro_sam and activated it.
Then I use: conda install -c conda-forge micro_sam napari pyqt
as described in the installation manual.

What happens then:
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: /

The last line ('Solving environment') never stops, i.e. the slash keeps rotating forever.

I would really appreciate any help in this matter. Thanks and best,
Matthias

**Comment by anwai98** [comment]
Hi @mocherry,

Thanks for your interest in `micro-sam`.

We recommend using `mamba` (it's just a drop-in replacement of `conda`, but much faster) to install the packages in a new environment (be sure that you aren't installing packages to your `base` environment). Could you try reinstalling `micro-sam` using the hints [here](https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#from-mamba)?

**Comment by constantinpape** [comment]
In addtion to what @anwai98 mentioned: it might be necessary to add pytorch to the conda channels, i.e. change the installation command to
```
conda install -c pytorch -c conda-forge micro_sam napari pygt
```
or (using mamba)

```
mamba install -c pytorch -c conda-forge micro_sam napari pygt
```

**Comment by martinschorb** [comment]
I also struggle with installation both on Windows and Linux.
Tried both `mamba` commands from the docs (CUDA and non-GPU). 
When I try to open the annotator in both, I end up with:

```
envs/micro-sam/lib/python3.11/site-packages/micro_sam/sam_annotator/annotator.py", line 5, in <module>
    import magicgui
ModuleNotFoundError: No module named 'magicgui'
```

that's directly after creating the environment:
`>mamba create -c pytorch -c nvidia -c conda-forge -n micro-sam micro_sam pytorch pytorch-cuda=12.1`
`>mamba activate micro-sam`
`>micro_sam.annotator`

when trying `mamba install -c conda-forge magicgui` 
I get: `All requested packages already installed`

That's very interesting and unexpected...

I then started messing around:
`pip install magicgui`
and `mamba install pyqt`

leads to 

```
site-packages/micro_sam/sam_annotator/annotator_2d.py", line 4, in <module>
    import napari
ModuleNotFoundError: No module named 'napari'
```

so yet another one: `mamba install napari -c conda-forge`

and finally it opens.

What am I doing wrong? Or is there something missing or wrong in the dependencies/environment definition?

**Comment by mocherry** [comment]
So if this were the way, it would definitively be too complicated for me.
In my case, even after using the suggestions of Constatin, the problem with resolving the environment persists: The last line ('Solving environment') never stops, i.e. the slash keeps rotating forever.

Cheers,
Matthias

**Comment by anwai98** [comment]
Hi @mocherry,

Can you try the following scripts and let us know if the issue persists for you:

(I tested the script below just now in a new fresh environment)
```
mamba create -n fresh-micro-sam
mamba activate fresh-micro-sam
mamba install -c pytorch -c conda-forge micro_sam
mamba install -c conda-forge napari pyqt
```

**Comment by martinschorb** [comment]
> 
> This seems like you were trying to run the annotator tool. For this, it's expected to install napari [in addition](https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#from-mamba) to the micro-sam installation. (something in the line of my suggested installation above)
> 
> Thanks for reporting your experience. We will extend the documentation further to explicitly mention the requirements. Happy to hear that `micro-sam` works for you now!

Ok, yes, that explains it. `napari` and  `pyqt` need to be installed (after `micro-sam`?).

**Comment by anwai98** [comment]
> Ok, yes, that explains it. `napari` and `pyqt` need to be installed (after `micro-sam`?).

In case it's desired to make use of the annotator tool, yes exactly!

**Comment by mocherry** [comment]
Hi@anwai98,

thanks. seems to work. At least I can start playing around.
One more question right now: do I always have to start with automatic segmentation? In the case of EM images this produces too many objects and it is quite tedious to remove the wrong ones. Can I instead start with point or box segmentation? 

@constantinpape thanks for your help so far and thanks for this great tool. I am sure it will be be widely used, especially if you can create an installer for Windows which not only the snake afficionados (anaconda, mamba) can get up and running. After all biologists who grew up before this snake-plague have interesting biological question but little programming capabilities ;-)

**Comment by anwai98** [comment]
Hi @mocherry,

Happy to hear that the installation worked for you.

> Can I instead start with point or box segmentation?

You have the choice to use the `Automatic Segmentation` option, or use points or boxes for interactive segmentation.

The quickest way to get started with interactive segmentation would be the following:
1. Open your image in the `micro_sam` annotation tool.
2. For boxes: Select the `prompts` layer in the `layer list` in the widget bar on the left.
  i. Select the :white_square_button: (`Add rectangles (R)`) option in the `layer controls` widget bar on top-left. Now, you can start making box annotations on your image, and press `Segment Object (S)` on the right widget bar.
3. For points: Select the `point_prompt` layer in the `layer list`.
  i. Select the :heavy_plus_sign: (`Add points (2)`) option in the `layer controls` widget bar on top-left. Now, you can place a point on your object of interest, and change the choice of point using `positive` or `negative` options in the `prompt` drop-down menu on the top-right of the right widget. Once you have placed your points, you can press `Segment Object (S)` on the right widget bar.
4. In both the methods mentioned above, there's the option to add further points after segmenting the objects once. So just keep repeating point `3.` until you've obtained your desired segmentation.

Here are details on how to use the annotation tool for [2d images](https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#annotator-2d) and [3d volumes](https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#annotator-3d) (the links have tutorial videos for quick tutorials on using the annotation tool for interactive segmentation).

**Comment by constantinpape** [comment]
Thanks for the detailed answer @anwai98 :). Just as an executive summary, @mocherry: you don't have to start with the automatic segmentation, and indeed there are many settings where it is advised not to do that.

> I am sure it will be be widely used, especially if you can create an installer for Windows which not only the snake afficionados (anaconda, mamba) can get up and running.

Thanks! And we know that we need to make installation easier! Unfortunately all of this takes some time ;). 

Overall, any feedback and questions are appreciated, so we know what to improve or explain better :).

**Comment by constantinpape** [comment]
I think the immediate problems with the windows installation are fixed. We will work on documenting this better and providing an alternative mode of installation for the next release (within the next two weeks.)
