### ISSUE TITLE
enable to hold tiled embeddings in memory

### ISSUE THREAD

**Issue by lufre1** [computational-cell-analytics/micro-sam#426]
At the moment tiled embeddings need to be stored to the drive. It should also be possible that tiled embeddings are hold in the memory.
See https://github.com/computational-cell-analytics/micro-sam/blob/master/micro_sam/util.py

**Comment by lufre1** [comment]
maybe this can help: https://zarr.readthedocs.io/en/stable/api/storage.html#zarr.storage.MemoryStore

**Comment by constantinpape** [comment]
Implemented in #429.
