### ISSUE TITLE
3d annotator segment object error

### ISSUE THREAD

**Issue by lufre1** [computational-cell-analytics/micro-sam#430]
on dev branch with 3d annotator segment object throws an error when using "Segment All Slices [Shift-S]":  
Steps to reproduce:
- dev branch
- lucchi++ 3d dataset (SA for microscopy example data)
- compute image embeddings with tiling (I tested with new in-memory and directory storage - memory storage only available in https://github.com/computational-cell-analytics/micro-sam/issues/426)
- verify that segmentation works:
  - test with "Segment Slice" 
- test with "Segment All Slices [Shift-S]"

Here is the error I got initially:
[dev_3d_annotater_lucchi_++_segment_all_slices_error.txt](https://github.com/computational-cell-analytics/micro-sam/files/14573834/dev_3d_annotater_lucchi_%2B%2B_segment_all_slices_error.txt)

**Comment by constantinpape** [comment]
Ok, I figured out why and this has actually never worked before. I will fix it later.
