### ISSUE TITLE
Issues while opening napari on Mac

### ISSUE THREAD

**Issue by Marei33** [computational-cell-analytics/micro-sam#441]
When I run the 3d annotator on my Mac, while opening napari another window opens up showing only a blurred white box that cannot be closed. I can switch to napari with exiting the full screen view, but it stays there all the time napari is open. 
Also, I get the message: `2024-03-14 09:18:05.545 python3.10[54867:4006730] not in fullscreen state`

It looks like this:
![Screenshot 2024-03-14 at 09 17 39](https://github.com/computational-cell-analytics/micro-sam/assets/86373668/d11f8c76-62e7-45c6-b251-5b963549553b)

**Comment by constantinpape** [comment]
We should double check this and document the issue if it's related to a specific MAC version:
- @Marei33 can you check this again on your personal and work MAC and report if this issue occurs on both or only on your work one?
(My assumption is that this only happens on an M3, but I want to double check)

**Comment by Marei33** [comment]
@constantinpape This screen no longer opens!
