### ISSUE TITLE
Make `image_series_annotator` flexible

### ISSUE THREAD

**Issue by anwai98** [computational-cell-analytics/micro-sam#444]
Update the `image_series_annotator` to:
- consider a volume and index per slice
    - this helps in annotating multiple objects in one slice, in the 2d annotation heuristic.
- consider a list of volumes and index per volume (needs 3d annotator) (i.e. set of z-stacks which the user wants to annotate the desired rois)
    - this helps in annotating the desired set of slices (for instance, the user knows that they have meaningful rois only in slices 10-15, 20-30 and 55-70)

**Comment by anwai98** [comment]
@constantinpape I observed something in `image_series_annotator`. The committed segmentations from previous images are still overlayed for the next images. Is this intended?

**Comment by constantinpape** [comment]
> The committed segmentations from previous images are still overlayed for the next images. Is this intended?

Yes, there was an issue when the AMG was uninitialized, which lead to an error before the segmentation was cleared.
Will be fixed in #456

**Comment by constantinpape** [comment]
Done in  #454
