### ISSUE TITLE
Clear annotations for the current layer in multi-dimensional segmentation

### ISSUE THREAD

**Issue by anwai98** [computational-cell-analytics/micro-sam#446]
The current setup clears annotations for all slices in multi-dimensional segmentation. It would be nice if the user has the choice to clear annotations only for the current slice (or all slices) flexibly, without losing the other marked prompts in other slices.

Something like (or vice-versa): `Clear Annotations` [✔️] `All Slices`

**Comment by constantinpape** [comment]
Fixed by #447
