### ISSUE TITLE
DistributedDataParallel

### ISSUE THREAD

**Issue by sladenheim** [computational-cell-analytics/micro-sam#472]
This is more of a question than an issue.

Does the micro-sam trainer allow for distributing models across multiple GPUs? In other words, does the torch_em default trainer use DataDistributedParallel?

**Comment by constantinpape** [comment]
Unfortunately we don't support it yet, but we plan to add it. Can you also create an issue in `torch_em` about this?
Thanks!

**Comment by sladenheim** [comment]
Sure, not a problem. Thanks for letting me know.

**Comment by constantinpape** [comment]
Pending https://github.com/constantinpape/torch-em/issues/229

**Comment by constantinpape** [comment]
This is now supported. We will work on documenting it. See also https://github.com/constantinpape/torch-em/issues/448
