### ISSUE TITLE
add collapsibility to gui sections

### ISSUE THREAD

**Issue by lufre1** [computational-cell-analytics/micro-sam#478]
## Description
At the moment the GUI of the annotater is divided into five sections (widgets):
- embeddings
- segment
- amg 2d / amg 3d
- commit
- clear  

![Screenshot from 2024-03-25 10-18-29](https://github.com/computational-cell-analytics/micro-sam/assets/155526548/67de152a-9de6-4955-90ec-1fca206ae426)

And these sections are displayed upon annotater start. This results in visual cluttering.
## Solution
Make sections collapsible and only display relevant sections upon annotater start.

**Comment by constantinpape** [comment]
Done in #486
