### ISSUE TITLE
Helper texts for menu options in annotator tool

### ISSUE THREAD

**Issue by anwai98** [computational-cell-analytics/micro-sam#487]
It would be nice to have hints (helper pop-ups) while hovering over a menu option. It's called tooltip messages in magicgui. Here's an example integration from empanada: https://github.com/volume-em/empanada-napari/blob/main/empanada_napari/_slice_inference.py#L89-L102

**Comment by constantinpape** [comment]
This is implemented now by #524. (Not all tooltips are finalized but the mechanism is fully implemented.)
