### ISSUE TITLE
Error executing micro_sam.sam_annotator.annotator_2d

### ISSUE THREAD

**Issue by aja9675** [computational-cell-analytics/micro-sam#502]
I am trying to run the 2D annotator as follows:
python3 -m micro_sam.sam_annotator.annotator_2d -i <path to image>

But this results in the following error:
<frozen runpy>:128: RuntimeWarning: 'micro_sam.sam_annotator.annotator_2d' found in sys.modules after import of package 'micro_sam.sam_annotator', but prior to execution of 'micro_sam.sam_annotator.annotator_2d'; this may result in unpredictable behaviour

I installed from source via mamba.

**Comment by anwai98** [comment]
Hi @aja9675, could you try running the annotator tool using the exposed [console scripts](https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#annotation-tools)?

For the desired outcome from above, you could run the following in command line:
`$ micro_sam.annotator_2d -i <PATH_TO_IMAGE>.ext`

Let us know if this works.

**Comment by aja9675** [comment]
Hi @anwai98, thanks very much for the quick response. That works for me.
