### ISSUE TITLE
napari not responding with larger models

### ISSUE THREAD

**Issue by lufre1** [computational-cell-analytics/micro-sam#536]
## Description
When computing embeddings with a larger model than "vit_t", napari tends to not respond. 
![Screenshot from 2024-04-24 10-20-37](https://github.com/computational-cell-analytics/micro-sam/assets/155526548/b48c0d47-1665-4d20-a9f6-3a490e1a6946)

**Comment by constantinpape** [comment]
There isn't anything we can do about this / this is likely only happening the first time on model download.
