### ISSUE TITLE
Windows Installer Error

### ISSUE THREAD

**Issue by anwai98** [computational-cell-analytics/micro-sam#541]
@lufre1 @constantinpape
I could reproduce the error we spotted here: https://github.com/computational-cell-analytics/micro-sam/issues/381 (also reported by @Sagnik700) and found a fix to it as well.

TLDR: error encountered - `RuntimeError: Freetype library not found` (detailed error report sent to @lufre1)

Fix:
1. Put the `freetype.dll` library file to `.\micro_sam\Scripts\` from [here](https://www.dll-files.com/freetype.dll.html)
    i. Unzip the installed `freetype.zip`'s `freetype.dll` to the above mentioned folder
3. Rerun the script from command line:`.\micro_sam.annotator_2d.exe -i ..\<IMAGE>.tif -m vit_b`. (IT WORKS!)

Would it make sense to find a way to add the missing library in the windows installer?

**Comment by lufre1** [comment]
I would suggest adding the .dll file to the installer. There might be an alternate solution to download the .dll when the installer is executed. I will check how reliable each solution is. Also, I will check how reliable downloading the .dll file during build or during install processes is.

**Comment by anwai98** [comment]
@lufre1 The latest windows installer works seamlessly (tested it for 2d annotator using command line). Thanks!

A few mentions (not sure if they are because of my system or something regarding the installer, would leave the mentions anyways)
- While the installation happens, the step for "Setting the package cache" takes a very-very long time
- Once all the installations are done, the step for "Clearning the package cache" takes an equally long amount of time

PS: My system config is - WIndows 10 Pro, Intel i5 7th Gen, 8GB RAM (has HDD disk storage)

**Comment by lufre1** [comment]
The post_install.bat and the reference to it in construct.yaml is missing. This might cause the error reoccurring again
