### ISSUE TITLE
Finalizing documentation for v1.0

### ISSUE THREAD

**Issue by constantinpape** [computational-cell-analytics/micro-sam#566]
- [x] [Annotation tools](https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#installation): Add links to videos.
- [x]  [Installer](https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#from-installer)
    - [x] update the links to new installers (pending building and uploading them)
    - [x] update the description of installation @anwai98 
- [x] [Tips & Tricks](https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#tips-tricks) and [Known Limitations](https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#known-limitations): Remove in favor of FAQ, see #511 
- [x] [Finetuned models](https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#finetuned-models): add the links to bioimage.io / zenodo (pending full publication of the models)
- [ ] [Choosing a model](https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#choosing-a-model): extend this to give more concrete recommendations
- [x] Add a table with the tested resources and corresponding training settings to the doc (based on the table from Supp. Fig. 12) cc @anwai98 
- [x] Add a description of what we need for training data (= instance segmentations); explain that we need dense segmentation for training the decoder, but that sparse segmentation is ok for just finetuning SAM. cc @anwai98 
- [x] Add some short comment on how to validate your finetuned model (in the FAQ?!) cc @anwai98 
- [x] [Contribution Guide](https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#contribution-guide)
    - [x] Add documentation of release process
    - [x] Update the rest
- [x] Proofread and improve formulations in [notebooks](https://github.com/computational-cell-analytics/micro-sam/tree/master/notebooks); add a Readme.
- [x] Proofread everything in doc and improve formulations!

Also pending #501

**Comment by constantinpape** [comment]
Usage in other tools! (QuPath plugin, DeepMIB). Don't have to add it right away but should add it soon.

**Comment by anwai98** [comment]
Adding the Zenodo links for the uploaded models here:
- LIVECell specialist: https://zenodo.org/records/11115426

**Comment by anwai98** [comment]
- > at: CP - Also relevant: https://github.com/computational-cell-analytics/micro-sam/issues/197 on parameter documentation, which has some relevant links.
