### ISSUE TITLE
Fix windows installer

### ISSUE THREAD

**Issue by constantinpape** [computational-cell-analytics/micro-sam#570]
The windows installer build is now failing because it can't find the updated logo path. Not sure why. See https://github.com/computational-cell-analytics/micro-sam/actions/runs/8909797016/job/24467788404.

In addition there is a link to the outdated `micro-sam-logo.ico` [here](https://github.com/computational-cell-analytics/micro-sam/blob/master/deployment/windows_menu_setup.py) and [here](https://github.com/computational-cell-analytics/micro-sam/blob/master/deployment/windows_menu.json). This should be updated as well.

**Comment by lufre1** [comment]
i used imagemagick cli tool to convert png to ico with: `convert logo.png -define icon:auto-resize=64,48,32,16 logo.ico`

**Comment by lufre1** [comment]
I reopened the issue:
As @anwai98 reported: Interactive segmentation works, but some error trace regarding the freetype pacakge occurs in the logs.
