### ISSUE TITLE
Question: openly available training materials?

### ISSUE THREAD

**Issue by haesleinhuepf** [computational-cell-analytics/micro-sam#616]
Hi @constantinpape ,

I'd like to talk about micro-sam in my teaching course at the university and I`m seaching for slides, I could possibly reuse. I would like to reshare them unter a CC-BY license (in [this repository](https://github.com/ScaDS/BIDS-lecture-2024)) and would of course acknowledge the original authors. 

Are there slides about micro-sam available online, e.g. on Zenodo or F1000?

Big thanks!

Best,
Robert

**Comment by constantinpape** [comment]
I have two presentations that I can share. (Have to double check later if I need to remove something but can share it in the evening.)

> Are there slides about micro-sam available online, e.g. on Zenodo or F1000?

I can upload them to zenodo. What's the best practice, upload as pdf or as pptx?

**Comment by haesleinhuepf** [comment]
Fantastic @constantinpape !!

pptx would be great! I could then just copy-paste slides and figures. I also often upload PDFs as well, because these can be rendered as preview in zenodo.

**Comment by constantinpape** [comment]
I have uploaded two recent talks here: https://zenodo.org/doi/10.5281/zenodo.11265037

**Comment by haesleinhuepf** [comment]
Fantastic, thanks so much @constantinpape ! 🤩
