### ISSUE TITLE
CUDA Error :  status execution failed when calling cublasLTMatmul

### ISSUE THREAD

**Issue by CRS1601** [computational-cell-analytics/micro-sam#633]
![WhatsApp Image 2024-06-10 at 15 33 01](https://github.com/computational-cell-analytics/micro-sam/assets/60772563/0c73876c-dcc7-4df8-a15f-1db1e941a23d)
I am trying to run the provided notbook on the sample data using GPU Tesla V4 on GCP and getting this error. I searched the internet which say there is a mismatch in shape of the embedding layers.
But the model runs perfectly fine while using CPU.

Please anyone can help me resolve the issue.

**Comment by anwai98** [comment]
Hi @CRS1601,

Thanks for your interest in `micro-sam`.

Could you help us with a few details to figure out the issue better:
- Can you tell us which [notebook](https://github.com/computational-cell-analytics/micro-sam/tree/master/notebooks) are you trying to run, and in which part of the code are you getting the error?
- Can you run the following script in your GCP GPU kernel for us and share the outputs to have a better idea of your PyTorch setup:
  ```python
  import torch
  print(torch.__version__)
  print(torch.version.cuda)
  print(torch.cuda.is_available())
  print(torch.cuda.get_device_name())
  ```

**Comment by CRS1601** [comment]
Hi @anwai98,

I am using the "automatic_segmentation.ipynb" notbook.

Please find the below outputs
import torch
print(torch.__version__)
1.3.1+cu117

print(torch.version.cuda)
11.7

print(torch.cuda.is_available())
True

print(torch.cuda.get_device_name())
'Tesla T4'

**Comment by anwai98** [comment]
Hi @CRS1601,

Most of the articles I found over the internet hint around updating the `pytorch` versions to the latest build. I also spotted in the [Segment Anything](https://github.com/facebookresearch/segment-anything#installation) repo that they recommend using `pytorch>=1.7`.

Could you try to update your pytorch version and let us know if the error is still there?

**Comment by constantinpape** [comment]
This seems to be resolved. Feel free to reopen if the issue persists.
