### ISSUE TITLE
Pin specific build string for nifty in yaml

### ISSUE THREAD

**Issue by anwai98** [computational-cell-analytics/micro-sam#687]
I explored a bit on this. Turns out, there is not really an elegant way to pin a desired build version with flexibility, it needs to match exactly what we see - with the hash and the build number (most discussions recommend testing this using `conda search nifty` and use the displayed build string according to our supported / desired python version), OR use wildcards (i.e. matching characters roughly to our desired builds - say we know build version 4 works, the build string would go as `*_4`).

Hence, the download could be made in a slightly simpler way besides the entire build string using `mamba install -c conda-forge nifty=1.2.1=*_4`.

**Comment by constantinpape** [comment]
I think the wild card is the best solution.
Did you check if it's possible to also put this in the yaml? It should be possible, but would be good to check.

**Comment by anwai98** [comment]
I'll check it right away and create a PR, in case it works!
