### ISSUE TITLE
Installing micro-sam from conda-forge fetches nifty build version 5

### ISSUE THREAD

**Issue by anwai98** [computational-cell-analytics/micro-sam#693]
I tested installing `micro-sam` from conda-forge. Turns out, it fetches build version 5 for nifty. Should I update the [recipe](https://github.com/conda-forge/micro_sam-feedstock/blob/main/recipe/meta.yaml) to trigger for the wildcard solution over conda-forge installation?

cc: @constantinpape

**Comment by anwai98** [comment]
Also pin napari < 0.5

**Comment by constantinpape** [comment]
Done.
