### ISSUE TITLE
Compatibility issues with napari 0.5

### ISSUE THREAD

**Issue by constantinpape** [computational-cell-analytics/micro-sam#695]
Napari 0.5 has some compatibility issues we should fix. Here are the ones @anwai98 found so far:
- [x] Keybindings don't work anymore
- [x] Box prompts are not cleared after committing the segmentation
- [x] The input image seems to flicker (appear and disappear) after committing a few segmented objects
- [x] Commit doesn't clear annotations (I think this is related to the first point)
- [x] Current image is still show in Image series annotator

**Comment by constantinpape** [comment]
Another thing I just noticed: interactive 3d segmentation for me became very slow. Need to double check this, not sure if it is related to the napari upgrade.

**Comment by rodrigo-pena** [comment]
I've also experimented some of these issues when using `Image Series Annotator` (`napari=0.5.3` from `conda-forge`). 

On top of that, sometimes when pressing `Commit` to commit current annotations, the current layer will not be cleared. 

Also, sometimes after pressing `Next Image` the current image will linger, and only by pressing `Next Image` again the next one will show up. This last step however raises a warning that "The current object has no annotations. Do you wish to continue?" (paraphrasing), leading to confusion as to whether some image I haven't seen will be left with blank annotations.

**Comment by anwai98** [comment]
Hi @rodrigo-pena,

Thanks for reporting the issue. I'll add this in the list of issues we have spotted and keep an eye to take care of this as well. Meanwhile, we have updated the installation from source and conda-forge to work with napari < 0.5. I can recommend you to do the same.

**Comment by rodrigo-pena** [comment]
Thanks, @anwai98. I will do that

**Comment by constantinpape** [comment]
I worked a bit on this:
- The issue with the shape layer is fixed in #696. I think this also fixes the issues reported with the image series annotator reported by @rodrigo-pena , but we should double check this again.
- The keybinding issue seems to be due to a regression in napari, see https://github.com/napari/napari/issues/7302 .

**Comment by constantinpape** [comment]
The keybinding issue will be fixed by #711

**Comment by constantinpape** [comment]
The initial issues are now all solved and we are preparing  new release. There still exist some other issues with napari:
- Clearing the shape layer is still not working perfectly. This is actually an issue in napari that will hopefully be fixed soon. See https://forum.image.sc/t/how-to-clear-shape-layer-in-napari/103785 for more details.
- Napari threadworker slows down things massively. For now it's deactivated. See #739 for details.

**Comment by constantinpape** [comment]
This should all be fixed now.
