### ISSUE TITLE
Fail to run a custom model

### ISSUE THREAD

**Issue by bpavie** [computational-cell-analytics/micro-sam#706]
Hi,

I tried to run a custom model with the napari interface without success.

The model has been taken from the one automatically downloaded and saved in the cache

I also re-download it from https://zenodo.org/records/10524791/files/vit_b_lm.pth?download=1

![image](https://github.com/user-attachments/assets/84043084-8f95-4d99-b3ce-b42f2e5d002a)

I get an error once I press "Compute Embeddings" and have select the "custom weights path"

Please find the log in attachment
[sam_logs_error.txt](https://github.com/user-attachments/files/17167387/sam_logs_error.txt)

**Comment by anwai98** [comment]
Hi @bpavie,

You need to choose the right model under the `Model` menu on the top-right of the widget (i.e. since you are willing to use `vit_b_lm` model checkpoints, you need to select `vit_b_lm` in the drop down)

Could you try this and let us know if this fixes the issue?

**Comment by bpavie** [comment]
Ah, ok, it works indeed. Would it be possible to add this to the documentation? We install micro-SAM on our HPC and people are using it via ondemands, but their home storage is very limited so that would be best for them to store the models on e.g. SCRACTH
Thanks!

**Comment by anwai98** [comment]
Hi @bpavie, happy to hear that it works now.

Re: add to documentaion: What do you mean by this? Did you mean that we should document the possibility of adding custom model weight paths to model weights stored in a desired directory?

**Comment by constantinpape** [comment]
I think this is fixed. Feel free to re-open if the issue persists or open a new issue if some other problem arises.
