### ISSUE TITLE
Add suggestions in finetuning notebook for samplers and sampling attempts

### ISSUE THREAD

**Issue by anwai98** [computational-cell-analytics/micro-sam#713]
Would be nice to hint users towards the use of samplers and increasing sampling attempts in case it fails. This would increase the autonomy of our notebooks.

**Comment by constantinpape** [comment]
I think we should first switch to the functionality in `micro_sam.training` in the notebook, since this can take care of many of these problems internally.

**Comment by anwai98** [comment]
The current state of our [finetuning notebook](https://github.com/computational-cell-analytics/micro-sam/blob/master/notebooks/sam_finetuning.ipynb) already makes use of `train_sam` in `micro_sam.training`. It probably needs the latest updates from `dev` (if any).

![image](https://github.com/user-attachments/assets/d92384df-2e6d-4b04-9754-c1ee7b1441b8)

**Comment by anwai98** [comment]
This is taken care of at https://github.com/computational-cell-analytics/micro-sam/pull/720.
