### ISSUE TITLE
SAM finetuning empty patches

### ISSUE THREAD

**Issue by maartenpaul** [computational-cell-analytics/micro-sam#721]
I'm running the SAM finetuning notebook to train the model on my images (https://github.com/computational-cell-analytics/micro-sam/blob/master/notebooks/sam_finetuning.ipynb). I do run into the problem that in some cases there are empty patches in the dataset, just because it happens that not the entire image is covered with objects. As soon as these patches are used the training crashes. For now this can be resolved by changing the size of the patches to equal the complete image as long there are objects in every image. Would it be possible to include an additional check if there are any object to train on and otherwise skip the patch? Or would there be a better solution?

https://github.com/computational-cell-analytics/micro-sam/blob/master/notebooks/sam_finetuning.ipynb

**Comment by maartenpaul** [comment]
Hi @anwai98 
Thanks for your quick response. Sorry I have missed your earlier conversations on this topic, those are already very helpful.

> Can you tell us what's the shape of your images?
Those are 2D images of either 1024x1024 or 2048x2048 pixels.  

> Let us know if the solution works for you.
I have added 
`sampler=MinInstanceSampler(min_size=25),`
to the sample loader in my notebook and now I'm able to run with smaller patches without errors about empty patches.
Thanks!

**Comment by anwai98** [comment]
Hi @maartenpaul,
Thanks for the update. I'll go ahead and close this issue. Let us know if you come across any other issues.
