### ISSUE TITLE
Add vit_l_lm to model registry?

### ISSUE THREAD

**Issue by nicoleaudia** [computational-cell-analytics/micro-sam#734]
Hello, I have the following code:

```
model_type = 'vit_l_lm'
sam_model = get_trainable_sam_model(model_type=model_type, device=device)
```
 
When I run this, I get an error. It appears that vit_l_lm is not part of the model_registry, whereas other models like vit_b_lm and vit_l are. I confirmed this by calling get_model_names().

Just wondering if there is a reason vit_l_lm is not included, or if it is possible to add it. Thanks!

**Comment by anwai98** [comment]
Hi @nicoleaudia,

Thanks for your interest in `micro-sam`.

Our latest version does support `vit_l_lm`. I am a bit confused why you get the error. Could you run the following script in terminal and share with us the outputs: `python -c "from micro_sam.util import get_model_names; print(get_model_names())"`

To remove another suspicion, could you also share the terminal outputs by running `python -c "import micro_sam; print(micro_sam.__version__)"`?

**Comment by constantinpape** [comment]
This seems to be resolved. Please reopen if the issue persists.

**Comment by nicoleaudia** [comment]
Thanks for suggesting to check the version -- one of my virtual environments was using a different version than the others! Fixed that and no longer having this issue.
