### ISSUE TITLE
Issues with file download via owncloud

### ISSUE THREAD

**Issue by anwai98** [computational-cell-analytics/micro-sam#756]
I tried starting the annotator and while downloading the sample HeLA image, I could reproduce the issue on owncloud

```
ReadTimeout: HTTPSConnectionPool(host='owncloud.gwdg.de', port=443): Read timed out. (read timeout=5)
```

**Comment by anwai98** [comment]
Our sample images are hosted at owncloud only. Should be have a backup spot, or have it over Zenodo instead?

**Comment by constantinpape** [comment]
Outages of any online service happen (also on zenodo). We don't need to fix this.
