### ISSUE TITLE
Installation micro-sam for macOS M1

### ISSUE THREAD

**Issue by GesineMueller** [computational-cell-analytics/micro-sam#77]
The troubleshooting didn't work for me, but I have some adaptions for the installation on the M1 that worked:

```
git clone https://github.com/computational-cell-analytics/micro-sam
mamba create -c conda-forge python=3.10 pip -n sam
conda activate sam
mamba install icu=70.1
mamba install qt-main=5.15.4
mamba install pyqt=5.15.4
mamba install pytorch::pytorch torchvision torchaudio -c pytorch
mamba install -c conda-forge python-elf tqdm
mamba install -c conda-forge napari
cd micro-sam 
pip install git+https://github.com/facebookresearch/segment-anything.git
pip install -e .
```

I needed to install icu, qt-main and pyqt before installing everything else. 
[SAM-yml.zip](https://github.com/computational-cell-analytics/micro-sam/files/12071388/SAM-yml.zip)

**Comment by constantinpape** [comment]
Thanks for reporting this @GesineMueller! I hope that we will have a more stable way of installing micro_sam on mac soon.
In the meantime I will leave this issue open and have linked it in the troubleshooting section of the (new!) installation documentation: https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#from-source

**Comment by constantinpape** [comment]
These issues are fixed now, PyTorch can be installed normally for Mac M1 etc. now.
