### ISSUE TITLE
run  automatic segmentation on a volume using the CLI with  'Automatic Segmentation Settings', save the 'commited_objects' layer to file

### ISSUE THREAD

**Issue by jazberna1** [computational-cell-analytics/micro-sam#775]
Hi!

I started using the `micro_sam.annotator_3d` script to create embeddings. I was wondering if there is a way to also perform the `Automatic Segmentation` on a volume using the CLI. In other words suply the script with the `Automatic Segmentation Settings` and save the `commited_objects` layer to a file i.e. a tif.

This way the script could take the existing embeddings folder (or create them if not exist) as it does now but also run the automatic segmentation.

I would find this particularly useful if one has like me, many image volumes for which I already know suitable segmentation settings.

Apologies if this is already implemented. If it is, I would love to know how to do it.

Many thanks
Jorge

**Comment by anwai98** [comment]
Hi @jazberna1,

Thanks for your interest in `micro-sam`. Just to clarify, you would like to run automatic segmentation using CLI with custom parameters for automatic segmentation and store the segmentations as tif, right?

**Comment by anwai98** [comment]
Nice, thanks for the clarification.

This is now implemented in our automatic segmentation CLI for 3d volumes as well (see `micro_sam.automatic_segmentation -h` for details), where it accepts `-i` / `--input_path` for the input volume, and stores the outputs at `-o` / `--output_path` specified by the user.

**Comment by jazberna1** [comment]
Hi,

That's great. I'm just wondering how can I set the Automatic Segmentation Settings i.e. the 'min_object_size'

Jorge

**Comment by anwai98** [comment]
Ahha I see.

We allow parsing all the parameters for automatic segmentation via the CLI supported by the `generate` method (for [AIS](https://github.com/computational-cell-analytics/micro-sam/blob/master/micro_sam/instance_segmentation.py#L967-L975) and [AMG](https://github.com/computational-cell-analytics/micro-sam/blob/master/micro_sam/instance_segmentation.py#L508-L516)). As an example, you can pass them using `--min_mask_region_area 10 ...` for automatic segmentation using AMG.

PS. I discussed this briefly in [`image.sc`](https://forum.image.sc/t/automatic-segmentation-with-micro-sam-python-batch-command-line/104880/4) as well.

I hope that answers your question.

**Comment by jazberna1** [comment]
Hi @anwai98 !
Thanks! that worked very well.
closing this ticket.
