### ISSUE TITLE
Input structure for the micro_sam.sam_annotator.annotator_3d

### ISSUE THREAD

**Issue by GesineMueller** [computational-cell-analytics/micro-sam#81]
Hi,

I have used the annotator_3d a couple of weeks before using a 3D tiff file as an input:

```python
from skimage.io import imread, imsave
from micro_sam.sam_annotator import annotator_3d
imsave("3D.tif", data.astype("uint8"))
data = imread("3D.tif")
embed_path = None
annotator_3d(raw, embedding_path=embed_path)
```

However, following the same steps now, I get the error message: "ValueError(f"Invalid input image of shape {input_.shape}. Expect either 2D grayscale or 3D RGB image.") ValueError: Invalid input image of shape (32, 256, 256). Expect either 2D grayscale or 3D RGB image." (image of whole error message is linked)

In 2D the annotator_2d works for me. I am now unsure how to use the annotator_3d for 3D tiff stacks and would be grateful for any hints. My data is a 3D grayscale image stack (uint16) that I then resaved to uint8. I also tried out float32 or saving the stack to png, but this results in the loss of the 3D structure. 

Thanks a lot,
Gesine

<img width="1082" alt="image" src="https://github.com/computational-cell-analytics/micro-sam/assets/94179441/f8756323-ca18-4928-991f-f80c59f05a7c">

**Comment by constantinpape** [comment]
Hi Gesine,
thanks for reporting the error! Can you please do the follwoing:
- Make sure that your version of `micro_sam` is up-to-date (i.e. that you're using the latest commit from the `master` branch). 
- If it isn't please update and try again (I have changed a few things related to the image reading quite recently and maybe that already solves the issue).
- If it's already up-to-date or updating it doesn't fix the error: please upload a the volume where you get this issue and send me a link to it, so I can see how to fix it.

Thans!

**Comment by constantinpape** [comment]
Hi @GesineMueller ,
turns out that was just a bug in the code when using the 3d annotator without the embedding caching.
(Apparently I didn't run that code in a while and didn't check some of my recent changes in there ...)

It should all work now once you pull the latest version. Let me know if there are still any issues, or if something else goes wrong!
