### ISSUE TITLE
What arguments should be input for --tile and --halo in 2d_annotator?

### ISSUE THREAD

**Issue by ludalin-ucla** [computational-cell-analytics/micro-sam#92]
I am glad that the tiling function is incorporated into micro-sam now. While, when I try to use tiling, I found the help document (-h) is not very clear. For example, if I want to segment a large image into multiple smaller images of 512 x 512 pixels, with the halo 64 pixels outward from a single tile (the total area is 576 x 576 pixels), then what I should input?

It is also interesting that in tiling function, it is not possible to pass -e and I have to set up a directory for embedding. I wonder why.

**Comment by constantinpape** [comment]
> For example, if I want to segment a large image into multiple smaller images of 512 x 512 pixels, with the halo 64 pixels outward from a single tile (the total area is 576 x 576 pixels), then what I should input?

In this case you should pass `tile_shape=(512, 512)` and `halo=(32, 32)`. And we're working on a proper documentation to describe this.

> It is also interesting that in tiling function, it is not possible to pass -e and I have to set up a directory for embedding. I wonder why.

This should work. Can you give the example for where this doesn't work?

**Comment by ludalin-ucla** [comment]
Here are some of my attempts:

Here, I try to input the arguments for --tile_shape and --halo:
(micro-sam) REDMORSFAC29100:micro-sam ludalin$ micro_sam.annotator_2d -i ".../.../image.png" --tile_shape "(512, 512)" --halo "(32, 32)"
usage: micro_sam.annotator_2d [-h] -i INPUT [-k KEY] [-e EMBEDDING_PATH]
                              [-s SEGMENTATION_RESULT] [-sk SEGMENTATION_KEY]
                              [--show_embeddings] [--model_type MODEL_TYPE]
                              [--tile_shape TILE_SHAPE [TILE_SHAPE ...]]
                              [--halo HALO [HALO ...]]
micro_sam.annotator_2d: error: argument --tile_shape: invalid int value: '(512, 512)'
(micro-sam) REDMORSFAC29100:micro-sam ludalin$ micro_sam.annotator_2d -i ".../.../image.png" --tile_shape (512, 512) --halo (32, 32)
-bash: syntax error near unexpected token `('
(micro-sam) REDMORSFAC29100:micro-sam ludalin$ micro_sam.annotator_2d -i ".../.../image.png" --tile_shape tile_shape=(512, 512) --halo halo=(32, 32)
-bash: syntax error near unexpected token `('
(microsam) REDMORSFAC29100:micro-sam ludalin$ micro_sam.annotator_2d -i ".../.../image.png" --tile_shape 512, 512 --halo 32, 32
usage: micro_sam.annotator_2d [-h] -i INPUT [-k KEY] [-e EMBEDDING_PATH]
                              [-s SEGMENTATION_RESULT] [-sk SEGMENTATION_KEY]
                              [--show_embeddings] [--model_type MODEL_TYPE]
                              [--tile_shape TILE_SHAPE [TILE_SHAPE ...]]
                              [--halo HALO [HALO ...]]
micro_sam.annotator_2d: error: argument --tile_shape: invalid int value: '512,'

Only when I input a single number it seems to work, but later I found that it does not work either.

Here is if I do not put an embedding directory:
(microsam) REDMORSFAC29100:micro-sam ludalin$ micro_sam.annotator_2d -i ".../.../image.png" --tile_shape 512 --halo 32
/Users/ludalin/Desktop/micro-sam/micro_sam/sam_annotator/annotator_2d.py:257: UserWarning: You have not passed an embedding_path. Restarting the annotator may take a long time.
  warnings.warn("You have not passed an embedding_path. Restarting the annotator may take a long time.")
Traceback (most recent call last):
  File "/Users/ludalin/anaconda3/envs/napari-env/bin/micro_sam.annotator_2d", line 33, in <module>
    sys.exit(load_entry_point('micro-sam', 'console_scripts', 'micro_sam.annotator_2d')())
  File "/Users/ludalin/Desktop/micro-sam/micro_sam/sam_annotator/annotator_2d.py", line 259, in main
    annotator_2d(
  File "/Users/ludalin/Desktop/micro-sam/micro_sam/sam_annotator/annotator_2d.py", line 218, in annotator_2d
    IMAGE_EMBEDDINGS = util.precompute_image_embeddings(
  File "/Users/ludalin/Desktop/micro-sam/micro_sam/util.py", line 352, in precompute_image_embeddings
    assert save_path is not None, "Tiled prediction is only supported when the embeddings are saved to file."
AssertionError: Tiled prediction is only supported when the embeddings are saved to file.

**Comment by constantinpape** [comment]
You need to pass the two values separately, without any additional separators. So e.g. `--tile_shape 512 512`.
Furthermore you must give an embedding path when using tiling (because the tiled embeddings currently will always be saved to file).
Given your commands from above the following combination should work:
```
$ micro_sam.annotator_2d -i ../../image.png --tile_shape 512 512 --halo 32 32 -e some_embedding_path.zarr
```

**Comment by ludalin-ucla** [comment]
Thank you very much. Then how can I get or generate an embedding? Or may I find an extant one? Thanks.

**Comment by constantinpape** [comment]
> Then how can I get or generate an embedding? Or may I find an extant one?

The embeddings are computed automatically, and stored in a file that you specify with `-e`. It's important to use different files for different images.

**Comment by constantinpape** [comment]
I have now added some more explanation about tiling in the (new) documentation: https://computational-cell-analytics.github.io/micro-sam/micro_sam.html#tips-tricks

**Comment by constantinpape** [comment]
This is all documented now, so I am closing the issue. Feel free to reopen it if anything is still unclear.
